(in-package #:cl-llm-provider-api/tests)

(defun test-output-contract-roundtrip ()
  "Test recursive native schemas, exact JSON types, and tagged portable values."
  (let* ((schema
           (output-schema-normalize
            '(:type :object
              :properties
              (("enabled" (:type :boolean))
               ("nothing" (:type :null))
               ("items" (:type :array
                         :items (:type :object
                                 :properties (("name" (:type :string))
                                              ("score" (:type :number)))
                                 :required ("name") :additional-properties nil)
                         :min-items 1 :max-items 2)))
              :required ("enabled" "nothing" "items") :additional-properties nil)))
         (provider-schema (output-schema->json schema))
         (candidate (output-json-decode
                     "{\"enabled\":false,\"nothing\":null,\"items\":[{\"name\":\"one\",\"score\":1.5}]}")))
    (check (output-schema-valid-p candidate schema) "recursive output validation failed")
    (check (and (string= (gethash "type" provider-schema) "object")
                (eq (gethash "additionalProperties" provider-schema) yason:false)
                (vectorp (gethash "required" provider-schema))
                (string= (gethash "type" (gethash "items" (gethash "items"
                          (gethash "properties" provider-schema)))) "object"))
           "native schemas did not project to recursive JSON Schema")
    (dolist (invalid '("{\"enabled\":null,\"nothing\":false,\"items\":[{\"name\":\"one\"}]}"
                       "{\"enabled\":false,\"nothing\":null,\"items\":[{\"name\":\"one\",\"extra\":1}]}"
                       "{\"enabled\":false,\"nothing\":null,\"items\":[]}"
                       "{\"enabled\":false,\"nothing\":null,\"items\":[{}, {}, {}]}"
                       "{\"enabled\":false,\"items\":[{\"name\":\"one\"}]}"))
      (check (not (output-schema-valid-p (output-json-decode invalid) schema))
             "invalid nested candidate was accepted")))
  (let* ((schema (output-schema-normalize '(:enum (nil :null t))))
         (enum (gethash "enum" (output-schema->json schema))))
    (check (and (= (length enum) 3) (eq (aref enum 0) yason:false)
                (eq (aref enum 1) :null) (eq (aref enum 2) t))
           "enum conversion conflated false and null")
    (dolist (text '("false" "null" "true"))
      (check (eq t (output-schema-valid-p (output-json-decode text) schema))
             "enum validation must return a boolean")))
  (let* ((json (output-json-decode
               "{\"z\":null,\"a\":[false,true,{\"quote\":\"a\\\"b\\n\"}],\"n\":2.5}"))
         (native (output-json->sexp json))
         (array (second (assoc "a" (rest native) :test #'string=))))
    (check (and (eq (first native) :object)
                (equal (mapcar #'first (rest native)) '("a" "n" "z"))
                (eq (first array) :array) (null (second array)) (eq (third array) t)
                (eq (second (assoc "z" (rest native) :test #'string=)) :null))
           "JSON did not convert to sorted portable tagged values")
    (check (equal native (output-json->sexp (output-sexp->json native)))
           "portable structured output did not round trip"))
  (dolist (text '("[]" "{}" "false" "null" "true" "0" "\"\""))
    (let ((native (output-json->sexp (output-json-decode text))))
      (check (equal native (output-json->sexp (output-sexp->json native)))
             "empty values or scalar identities were lost"))))

(defun test-output-contract-diagnostics ()
  "Test every supported schema field's structural and semantic failures."
  (dolist (case '((() :type)
                  ((:type :unknown) :type)
                  ((:type :integer :type :number) :type)
                  ((:type :integer :minimum 0) :minimum)
                  ((:type :integer :items (:type :string)) :items)
                  ((:enum ()) :enum)
                  ((:enum (1 1.0)) :enum)
                  ((:enum (1/2)) :enum)
                  ((:enum (#\x)) :enum)
                  ((:type :boolean :enum (nil :null)) :enum)
                  ((:type :object :enum ("x")) :enum)
                  ((:type :array :enum ("x") :items (:type :integer)) :enum)
                  ((:type :object :properties (("" (:type :string)))) :properties)
                  ((:type :object :properties (("x"))) :properties)
                  ((:type :object :properties (("same" (:type :string))
                                               ("same" (:type :integer)))) :properties)
                  ((:type :object :properties (("x" (:type :string))) :required ("x" "x")) :required)
                  ((:type :object :required ("missing")) :required)
                  ((:type :object :additional-properties :null) :additional-properties)
                  ((:type :array) :items)
                  ((:type :array :items (:type :integer) :min-items -1) :min-items)
                  ((:type :array :items (:type :integer) :max-items 1.0) :max-items)
                  ((:type :array :items (:type :integer) :min-items 2 :max-items 1) :max-items)))
    (destructuring-bind (schema expected-field) case
      (let ((condition (handler-case (progn (output-schema-normalize schema) nil)
                         (output-contract-error (condition) condition))))
        (check (and condition (eq (output-contract-error-field condition) expected-field))
               "invalid native schema field ~S lacks a typed diagnostic" expected-field))))
  (dolist (schema '((:type) ("type" :string) (:type . :string)))
    (check (handler-case (progn (output-schema-normalize schema) nil)
             (output-contract-error () t)) "malformed native schema list was accepted"))
  (let ((schema (list :type :array :items nil)))
    (setf (getf schema :items) schema)
    (check (handler-case (progn (output-schema-normalize schema :maximum-depth 8) nil)
             (output-contract-error () t)) "recursive schema cycle was accepted"))
  (let ((schema (list :type :integer)))
    (setf (rest (last schema)) schema)
    (check (handler-case (progn (output-schema-normalize schema) nil)
             (output-contract-error () t)) "circular schema list was accepted"))
  (dolist (options '((:maximum-nodes 2) (:maximum-depth 0) (:property-name-limit 1)))
    (check (handler-case
               (progn (apply #'output-schema-normalize
                             '(:type :object :properties (("long" (:type :string)))) options)
                      nil)
             (output-contract-error () t)) "schema structural bound was ignored")))

(defun test-output-contract-types ()
  "Test supported scalar types and exact false/null/array distinctions."
  (dolist (case '((:string "\"x\"" "1") (:integer "1" "1.5")
                  (:number "1.5" "\"1\"") (:boolean "false" "null")
                  (:null "null" "false") (:object "{}" "[]")))
    (destructuring-bind (type valid invalid) case
      (let ((schema (output-schema-normalize (list :type type))))
        (check (eq t (output-schema-valid-p (output-json-decode valid) schema))
               "a supported scalar was rejected")
        (check (null (output-schema-valid-p (output-json-decode invalid) schema))
               "a scalar with another type was accepted"))))
  (let ((schema (output-schema-normalize '(:type :number :enum (1 2.5)))))
    (check (output-schema-valid-p 1.0 schema) "numeric enums must compare under JSON equality")
    (check (not (output-schema-valid-p 2 schema)) "numeric enum admitted another number"))
  (dolist (schema '((:type :array :items (:type :integer) :max-items 0)
                    (:type :array :items (:type :integer) :min-items 0)))
    (check (output-schema-valid-p #() (output-schema-normalize schema))
           "zero array bounds must permit empty arrays")))

(defun test-output-value-failures ()
  "Test exact JSON framing and malformed portable output values."
  (dolist (text '("{\"complete\":true} false" "" "{" "[1," "\"unterminated"))
    (check (handler-case (progn (output-json-decode text) nil)
             (output-value-error () t)) "invalid JSON framing was accepted"))
  (dolist (native '((:object ("duplicate" 1) ("duplicate" 2))
                    (:object ("missing")) (:object (1 2))
                    ("untagged" nil :null) #\x 1/2))
    (check (handler-case (progn (output-sexp->json native) nil)
             (output-value-error () t)) "invalid tagged output tree was accepted"))
  (check (handler-case (progn (output-json->sexp #\x) nil)
           (output-value-error () t)) "unsupported provider value was accepted"))

(defun test-output-contracts ()
  "Run generic schema, validation, diagnostics and exact JSON tests."
  (test-output-contract-roundtrip)
  (test-output-contract-diagnostics)
  (test-output-contract-types)
  (test-output-value-failures))
