(in-package #:cl-llm-provider-api/tests)

(defun context-tests--value (identifier &rest options)
  "Construct a contribution with distinguishable instruction and evidence data."
  (apply #'make-context-contribution :identifier identifier
         :instruction (concatenate 'string "instruction-" identifier) options))

(defun context-tests--identifiers (selection)
  "Return the semantic selection's identifiers in delivery order."
  (mapcar #'context-contribution-identifier
          (context-selection-contributions selection)))

(defun test-context-selection ()
  "Test stacking, semantic deduplication, supersession, conflicts and required-first order."
  (let* ((resolver (make-context-resolver))
         (values (list
                  (context-tests--value "generic" :priority 5)
                  (context-tests--value "specific" :priority 20 :supersedes '("generic"))
                  (context-tests--value "stacked" :priority 10)
                  (context-tests--value "duplicate-low" :priority 1 :deduplication-key "duplicate")
                  (context-tests--value "duplicate-high" :priority 2 :deduplication-key "duplicate")
                  (context-tests--value "conflict-low" :priority 3 :conflict-group "mode")
                  (context-tests--value "conflict-high" :priority 4 :conflict-group "mode")))
         (selection (context-resolve values :resolver resolver :session-key "one")))
    (check (equal (context-tests--identifiers selection)
                  '("specific" "stacked" "conflict-high" "duplicate-high"))
           "compatible advice did not stack after generic resolution")
    (check (= 7 (length values)) "resolution mutated the caller's contribution list"))
  (let* ((required (context-tests--value "required" :class ':mandatory :priority -100
                                        :deduplication-key "key" :conflict-group "mode"))
         (values (list (context-tests--value "advice" :priority 1000
                                            :deduplication-key "key" :supersedes '("required"))
                       required
                       (context-tests--value "other" :priority 2000 :conflict-group "mode")))
         (selection (context-resolve values :resolver (make-context-resolver) :budget 0)))
    (check (equal (list required) (context-selection-contributions selection))
           "mandatory contributions must survive higher-priority advice and supersession"))
  (let ((values (list (context-tests--value "first" :deduplication-key "same")
                      (context-tests--value "second" :deduplication-key "same")
                      (context-tests--value "third" :conflict-group "group")
                      (context-tests--value "fourth" :conflict-group "group"))))
    (check (equal '("first" "third")
                  (context-tests--identifiers
                   (context-resolve values :resolver (make-context-resolver))))
           "equal priority must preserve input order"))
  (let ((values (list (context-tests--value "old" :deduplication-key "semantic")
                      (context-tests--value "new" :supersedes '("semantic")))))
    (check (equal '("new") (context-tests--identifiers
                            (context-resolve values :resolver (make-context-resolver))))
           "supersession must accept semantic keys as well as identifiers")))

(defun test-context-budget ()
  "Test injected costs, stable priority, omission and mandatory budget bypass."
  (let* ((mandatory (context-tests--value "mandatory" :class ':mandatory :priority -100))
         (large (context-tests--value "large" :priority 100))
         (small (context-tests--value "small" :priority 10 :evidence "untrusted data"))
         (last (context-tests--value "last" :priority 10))
         (calls nil)
         (selection
           (context-resolve
            (list last mandatory large small) :resolver (make-context-resolver)
            :budget 3 :cost-function (lambda (value)
                                      (push value calls)
                                      (if (eq value large) 4 2)))))
    (check (equal '("mandatory" "last") (context-tests--identifiers selection))
           "budget selection must continue after an oversized high-priority value")
    (check (equal (list large small) (context-selection-omitted selection))
           "omitted values lost stable budget order")
    (check (not (member mandatory calls)) "mandatory values must not call advisory costing")
    (check (and (string= (context-contribution-evidence small) "untrusted data")
                (string= (context-contribution-instruction small) "instruction-small"))
           "instruction and evidence must be separate values"))
  (dolist (cost '(-1 "invalid"))
    (check (handler-case
               (progn (context-resolve (list (context-tests--value "value"))
                                       :resolver (make-context-resolver)
                                       :cost-function (lambda (value) (declare (ignore value)) cost))
                      nil)
             (context-contribution-error () t))
           "invalid contribution cost must fail with a context condition")))

(defun test-context-receipts ()
  "Test successful delivery, retry, session isolation, reactivation and late completion."
  (let* ((resolver (make-context-resolver))
         (once (context-tests--value "once" :lifetime ':next-request))
         (values (list once)))
    (labels ((resolve (&optional (session "one") (budget 100))
               (context-resolve values :resolver resolver :session-key session :budget budget)))
      (let ((failed (resolve)))
        (declare (ignore failed))
        (check (equal '("once") (context-tests--identifiers (resolve)))
               "assembly alone must not consume receipts"))
      (let ((delivery (resolve)))
        (context-selection-complete delivery)
        (context-selection-complete delivery))
      (check (null (context-tests--identifiers (resolve))) "successful delivery did not consume once")
      (check (equal '("once") (context-tests--identifiers (resolve "two")))
             "one session's receipt must not consume another session's contribution")
      (context-selection-complete (resolve "two"))
      (context-resolve nil :resolver resolver :session-key "one")
      (check (equal '("once") (context-tests--identifiers (resolve))) "inactive advice did not reactivate")
      (check (null (context-tests--identifiers (resolve "two"))) "reactivation erased another session")
      (context-selection-complete (resolve "one" 0))
      (check (equal '("once") (context-tests--identifiers (resolve))) "omitted advice consumed a receipt")
      (let ((old (resolve)))
        (context-resolve nil :resolver resolver :session-key "one")
        (resolve)
        (context-selection-complete old)
        (check (equal '("once") (context-tests--identifiers (resolve)))
               "late completion consumed a later activation"))
      (let ((old (resolve)))
        (context-resolver-reset resolver :session-key "one")
        (resolve)
        (context-selection-complete old)
        (check (equal '("once") (context-tests--identifiers (resolve)))
               "completion after reset consumed a new activation"))
      (context-resolver-reset resolver)
      (check (equal '("once") (context-tests--identifiers (resolve "two")))
             "reset must clear all sessions when no key is supplied"))))

(defun test-context-values ()
  "Test public contribution bounds and supported lifetime values."
  (dolist (lifetime '(:next-request :turn :while-relevant :until-success))
    (check (eq lifetime (context-contribution-lifetime
                        (context-tests--value "valid" :lifetime lifetime)))
           "a supported lifetime was rejected"))
  (dolist (options (list '(:identifier "" :instruction "x")
                         '(:identifier "x" :instruction "")
                         '(:identifier "x" :instruction "x" :priority 1.5)
                         '(:identifier "x" :instruction "x" :class :unknown)
                         '(:identifier "x" :instruction "x" :lifetime :unknown)
                         '(:identifier "x" :instruction "x" :supersedes (1))
                         (list :identifier "x" :instruction "x" :evidence
                               (make-string (1+ *context-contribution-evidence-limit*)))
                         (list :identifier "x" :instruction
                               (make-string (1+ *context-contribution-instruction-limit*)))))
    (check (handler-case (progn (apply #'make-context-contribution options) nil)
             (context-contribution-error () t))
           "invalid contribution options were accepted"))
  (let ((references (list "one")))
    (setf (rest references) references)
    (check (handler-case (progn (context-tests--value "x" :supersedes references) nil)
             (context-contribution-error () t))
           "circular supersession references must be rejected")))

(defun test-context-assembly ()
  "Run generic context contribution, selection and receipt tests."
  (test-context-selection)
  (test-context-budget)
  (test-context-receipts)
  (test-context-values))
