(defpackage #:cl-llm-provider-api
  (:nicknames #:llm-provider-api)
  (:use #:cl)
  (:export #:*bounded-retry-delays*
           #:*bounded-retry-sleep-function*
           #:*character-read-sequence-window*
           #:*rlm-default-call-budget*
           #:*rlm-default-depth-budget*
           #:*rlm-default-token-budget*
           #:*rlm-output-reserve-share*
           #:*rlm-output-reserve-tokens*
           #:*sse-end-of-stream*
           #:*sse-maximum-event-characters*
           #:*sse-maximum-line-characters*
           #:*sse-read-line-function*
           #:*stream-limit-error-class*
           #:assistant-delta-event
           #:assistant-delta-event-text
           #:call-with-bounded-retries
           #:chat-completions-provider
           #:model-provider
           #:model-provider-registration
           #:provider-api-error
           #:provider-api-error-message
           #:provider-completed-event
           #:provider-completed-event-response-id
           #:provider-completed-event-turn-completion
           #:provider-completed-event-usage
           #:provider-consume-stream
           #:provider-family
           #:provider-event
           #:provider-item-event
           #:provider-item-event-item
           #:provider-native-compact-conversation
           #:provider-normalize-output-item
           #:provider-output-ceiling-p
           #:provider-progress-event
           #:provider-request-object
           #:provider-responses-hosted-tools
           #:provider-responses-instructions-placement
           #:provider-responses-reasoning-summary
           #:provider-responses-request-fields
           #:provider-responses-request-namespaces
           #:provider-responses-wire-effort
           #:provider-result
           #:provider-result-output-items
           #:provider-result-response-id
           #:provider-result-tool-calls
           #:provider-result-turn-completion
           #:provider-result-turn-state
           #:provider-resample-requested
           #:provider-resample-requested-attempt
           #:provider-resample-requested-maximum-attempts
           #:provider-resample-requested-triggers
           #:provider-result-usage
           #:provider-retry-event
           #:provider-retry-event-attempt
           #:provider-retry-event-delay
           #:provider-retry-event-maximum-attempts
           #:provider-retryable-error
           #:provider-set-reasoning-summaries
           #:provider-stream-limit-error
           #:provider-stream-turn
           #:provider-wire-input-item
           #:provider-wire-protocol
           #:provider-wire-tool
           #:provider-wire-tool-name
           #:provider-wire-tools
           #:provider-with-configuration
           #:provider-configuration
           #:provider-credential-manager
           #:provider-session-id
           #:read-character-sequence
           #:read-sse-data
           #:reasoning-delta-event
           #:reasoning-delta-event-text
           #:responses-api-provider
           #:rlm-budget
           #:rlm-budget-acquire-request
           #:rlm-budget-create
           #:rlm-budget-descend
           #:rlm-budget-exhausted
           #:rlm-budget-exhausted-dimension
           #:rlm-budget-exhausted-task
           #:rlm-budget-remaining-calls
           #:rlm-budget-remaining-depth
           #:rlm-budget-remaining-tokens
           #:rlm-budget-settle-output
           #:rlm-content-digest
           #:rlm-context-designator-object
           #:rlm-context-intern
           #:rlm-context-intern-pathname
           #:rlm-context-object
           #:rlm-context-object-characters
           #:rlm-context-object-content
           #:rlm-context-object-digest
           #:rlm-context-object-find
           #:rlm-context-object-label
           #:rlm-context-object-pathname
           #:rlm-context-store
           #:rlm-context-store-create
           #:rlm-context-store-root
           #:rlm-view
           #:rlm-view-content
           #:rlm-view-digest
           #:rlm-view-error
           #:rlm-view-error-designator
           #:rlm-view-error-message
           #:rlm-view-label
           #:rlm-view-materialize
           #:rlm-view-origin
           #:rlm-views-materialize
           #:rlm-views-render
           #:sse-data-line
           #:sse-read-line-characters
           #:subscription-provider
           #:turn-completion
           #:provider--call-with-transport-normalization
           #:provider-signal-http-failure
           #:response-item-reasoning-summary
           #:provider-result-assistant-text
           #:response-item-assistant-text
           #:responses-standard-instructions
           #:responses-developer-message
           #:provider-unauthorized
           #:response-stream-limit-error
           #:response-stream-error
           #:provider-transport-error
           #:provider-incomplete-response
           #:provider-protocol-error
           #:provider-error
           #:openai-compatible--fallback-tool-name
           #:openai-compatible--function-call-item
           #:openai-compatible--stream-tool-states
           #:openai-compatible--choice-tool-deltas
           #:openai-compatible--tool-delta-index
           #:openai-compatible--append-tool-delta
           #:openai-compatible-tool-state
           #:openai-compatible--delta-text
           #:openai-compatible--chat-context-message
           #:openai-compatible--chat-system-message
           #:openai-compatible--chat-input-messages
           #:openai-compatible--chat-input-item
           #:openai-compatible--chat-tool-output
           #:openai-compatible--chat-function-calls
           #:openai-compatible--chat-function-call-entry
           #:openai-compatible--chat-message
           #:openai-compatible--wire-call-name
           #:openai-compatible--chat-content
           #:openai-compatible--chat-content-part
           #:openai-compatible--wire-tools
           #:openai-compatible--standalone-wire-tool
           #:openai-compatible--wire-tool
           #:openai-compatible--wire-function
           #:openai-compatible--decode-wire-tool-name
           #:openai-compatible--wire-tool-name
           #:provider--signal-event-failure
           #:provider--signal-incomplete-response
           #:provider--event-incomplete-reason
           #:provider--signal-invalid-terminal-reason
           #:provider--signal-terminal-protocol-error
           #:*provider-incomplete-terminal-reasons*
           #:provider--signal-incomplete-terminal
           #:provider--condition-string
           #:provider-rate-limit-error-p
           #:provider--retryable-event-error-code-p
           #:provider--event-request-id
           #:provider--event-response-id
           #:provider--event-error-code
           #:provider--event-error-object
           #:provider--event-response
           #:provider--decode-sse-data
           #:provider--read-sse-data
           #:provider--signal-transport-failure
           #:provider--transport-failure-message
           #:provider--signal-stream-protocol-failure
           #:provider--signal-stream-interruption
           #:provider--reasoning-summary-key
           #:provider-note-doom-loop-event
           #:normalize-response-item
           #:provider--signal-http-status-failure
           #:provider-retryable-status-p
           #:provider--http-error-message
           #:provider--error-body-detail
           #:provider--response-request-id
           #:response-header
           #:provider--sanitize-wire-value
           #:provider--sanitize-wire-string
           #:*provider-active-credential-redaction-marker*
           #:*provider-active-credential-values*
           #:*provider-credential-redaction-marker*
           #:*provider-retryable-http-statuses*
           #:*provider-error-detail-limit*
           #:*provider-retryable-event-error-codes*
           #:*provider-rate-limit-event-error-codes*
           #:*provider-wire-function-name-maximum-length*
           #:provider-wire-function-name--literal-character-p
           #:provider-wire-function-name--valid-p
           #:provider-wire-function-name--escape-sequence-p
           #:provider-wire-function-name--encode-component
           #:provider-wire-function-name--decode-component
           #:provider-wire-function-name--encode
           #:provider-wire-function-name--decode-readable
           #:provider-wire-function-name--decode-legacy
           #:provider-wire-function-name--decode
           #:provider-usage--field
           #:provider-usage--nested-field
           #:provider-usage-normalize
           #:provider-error-status
           #:provider-error-code
           #:provider-error-request-id
           #:provider-error-response-id
           #:provider-error-response
           #:provider-incomplete-response-reason
           #:*provider-error-body-deadline-seconds*
           #:provider-call-with-response-deadline
           #:provider--close-response-stream
           #:provider--drain-error-body
           #:provider--error-body-text
           #:*openai-compatible-wire-tool-name-maximum-length*
           #:wire-request
           #:wire-request-model
           #:wire-request-items
           #:wire-request-prefix
           #:wire-request-suffix
           #:wire-request-options
           #:provider-execute-request
           #:provider-account-label
           #:provider-note-response-headers
           #:context-contribution
           #:context-contribution-lifetime
           #:context-contribution-class
           #:context-contribution-identifier
           #:context-contribution-instruction
           #:context-contribution-evidence
           #:context-contribution-priority
           #:context-contribution-deduplication-key
           #:context-contribution-supersedes
           #:context-contribution-conflict-group
           #:context-contribution-contributor
           #:context-contribution-source
           #:*context-contribution-identifier-limit*
           #:*context-contribution-instruction-limit*
           #:*context-mandatory-instruction-limit*
           #:*context-contribution-evidence-limit*
           #:*context-contribution-reference-limit*
           #:context-contribution-error
           #:make-context-contribution
           #:context-resolver
           #:make-context-resolver
           #:context-resolver-reset
           #:context-resolve
           #:context-selection
           #:context-selection-contributions
           #:context-selection-omitted
           #:context-selection-complete
           #:output-contract-error
           #:output-contract-error-field
           #:output-value-error
           #:output-schema-normalize
           #:output-schema->json
           #:output-schema-valid-p
           #:output-json-decode
           #:output-json->sexp
           #:output-sexp->json
           #:output-json-number-p
           #:anthropic-messages-provider
           #:context-contribution-token-estimate))

(in-package #:cl-llm-provider-api)
